version: '3.8'

services:
  voicevox:
    container_name: voicevox
    build:
        context: ./Docker/voicevox
        args:
          - VOICEVOX_VERSION=${VOICEVOX_VERSION}
          - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./Docker/voicevox/convert.sh:${APP_CODE_PATH_CONTAINER}/convert.sh
    ports:
      - "50021:50021"
    tty: true
