version: '3.8'

services:
  voicevox:
    container_name: voicevox
    build:
        context: ./Docker/voicevox
        args:
          - VOICEVOX_VERSION=${VOICEVOX_VERSION}
    volumes:
      - ./work:/work
    ports:
      - "50021:50021"
    tty: true
