name: Convert

on:
  push:
    branches:
      - convert/*

jobs:
  deploy:
    # Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 

      # Docker Set Up
      - name: Docker Set Up
        env:
          VOICEVOX_VERSION: cpu-ubuntu20.04-latest
        run: |
          docker-compose up -d --build
          docker-compose logs

      # Convert Exec
      - name: Convert Exec
        run: |
          docker-compose exec -T voicevox sh -c "cd /work && sh target.sh"

      # Upload Artifact
      - name: Convert Complete Upload
        uses: actions/upload-artifact@v2.2.0
        with:
          # 保存ファイル名（XXXX.zip）
          name: convert
          # 保存するファイル
          path: work/complete
          # 保存期間（日）
          retention-days: 3